<!--
Codes Generated By ebiz-lowcode:
http://www.ebiz-interactive.com/
-->

<template>
  <div class="home">
    <!-- 顶部区域 -->
    <div class="header-section">
      <div class="header">
        <div class="location">
          <span>{{ $t('home.location') }}</span>
          <van-icon name="arrow-down" color="#fff" />
        </div>
        <div class="header-right">
          <van-icon name="search" size="20" color="#fff" />
          <van-icon name="service-o" size="20" color="#fff" />
          <van-icon name="globe" size="20" color="#fff" @click="toggleLanguage" />
        </div>
      </div>
      <div class="banner-content">
        <h2>{{ $t('home.banner.title') }}</h2>
        <p>{{ $t('home.banner.subtitle') }}</p>
        <van-button round type="default" size="small" class="more-btn">{{ $t('home.banner.viewMore') }}</van-button>
      </div>
    </div>

    <!-- 待办事项 -->
    <div class="todo-section">
      <div class="todo-header">
        <div class="todo-left">
          <van-icon name="todo-list" color="#07c160" size="20" />
          <span>{{ $t('home.todo.title') }}</span>
          <span class="todo-count">{{ $t('home.todo.count', { count: 9 }) }}</span>
        </div>
        <van-button round type="warning" size="small">{{ $t('home.todo.followUp') }}</van-button>
      </div>
      
      <!-- 通知栏 -->
      <div class="notification-bar">
        <van-icon name="volume-o" color="#ff4d4f" />
        <span class="notification-text">{{ $t('home.todo.notification') }}</span>
        <van-icon name="arrow" />
      </div>
    </div>

    <!-- 功能图标区 -->
    <div class="function-grid">
      <div class="grid-item" v-for="(item, index) in functionList" :key="index">
        <div class="icon-wrapper" :style="{backgroundColor: item.bgColor}">
          <van-icon :name="item.icon" :color="item.iconColor" size="24" />
        </div>
        <span class="grid-text">{{ $t(item.name) }}</span>
      </div>
    </div>

    <!-- 生态专区 -->
    <div class="eco-section">
      <h3 class="section-title">{{ $t('home.eco.title') }}</h3>
      <div class="eco-grid">
        <div class="eco-item" v-for="(item, index) in ecoList" :key="index">
          <div class="eco-content">
            <h4>{{ $t(item.title) }}</h4>
            <p>{{ $t(item.desc) }}</p>
          </div>
          <img :src="item.image" :alt="$t(item.title)">
        </div>
      </div>
    </div>

    <!-- 底部导航栏 -->
    <tab-bar />
  </div>
</template>

<script>
import TabBar from '@/components/layout/TabBar.vue'

export default {
  name: 'Home',
  components: {
    TabBar
  },
  data() {
    return {
      functionList: [
        { name: 'home.functions.myPolicy', icon: 'description', bgColor: '#e8f5e9', iconColor: '#4caf50' },
        { name: 'home.functions.accountProgress', icon: 'chart-trending-o', bgColor: '#e3f2fd', iconColor: '#2196f3' },
        { name: 'home.functions.personalClaim', icon: 'balance-o', bgColor: '#f3e5f5', iconColor: '#9c27b0' },
        { name: 'home.functions.groupClaim', icon: 'shield-o', bgColor: '#e8eaf6', iconColor: '#3f51b5' },
        { name: 'home.functions.eNotice', icon: 'bell', bgColor: '#fff3e0', iconColor: '#ff9800' },
        { name: 'home.functions.formDownload', icon: 'down', bgColor: '#fbe9e7', iconColor: '#ff5722' },
        { name: 'home.functions.paymentReminder', icon: 'cash-back-record', bgColor: '#e0f2f1', iconColor: '#009688' },
        { name: 'home.functions.policyContract', icon: 'records', bgColor: '#f9fbe7', iconColor: '#cddc39' },
        { name: 'home.functions.changePlatformPhone', icon: 'phone-o', bgColor: '#fce4ec', iconColor: '#e91e63' },
        { name: 'home.functions.changeNetworkAccount', icon: 'setting-o', bgColor: '#f3e5f5', iconColor: '#9c27b0' },
        { name: 'home.functions.changeDefaultAccount', icon: 'card', bgColor: '#e8f5e9', iconColor: '#4caf50' },
        { name: 'home.functions.moreServices', icon: 'apps-o', bgColor: '#e3f2fd', iconColor: '#2196f3' }
      ],
      ecoList: [
        {
          title: 'home.eco.unionMember.title',
          desc: 'home.eco.unionMember.desc',
          image: require('@/assets/images/bg1.png')
        },
        {
          title: 'home.eco.bayArea.title',
          desc: 'home.eco.bayArea.desc',
          image: require('@/assets/images/bg1.png')
        },
        {
          title: 'home.eco.sports.title',
          desc: 'home.eco.sports.desc',
          image: require('@/assets/images/bg1.png')
        },
        {
          title: 'home.eco.rewards.title',
          desc: 'home.eco.rewards.desc',
          image: require('@/assets/images/bg1.png')
        }
      ]
    }
  },
  methods: {
    toggleLanguage() {
      const currentLang = this.$i18n.locale
      const newLang = currentLang === 'en-US' ? 'zh-HK' : 'en-US'
      this.$i18n.locale = newLang
      localStorage.setItem('language', newLang)
      
      // 更新 Vant 组件的语言
      const { Locale } = this.$vant
      if (newLang === 'en-US') {
        import('vant/es/locale/lang/en-US').then(msgs => {
          Locale.use('en-US', msgs.default)
        })
      } else {
        Locale.use('zh-HK')
      }
    }
  }
}
</script>

<style lang="scss" scoped>
.home {
  min-height: 100vh;
  background-color: #f5f5f5;
  padding-bottom: 50px;
}

.header-section {
  background-image: url('~@/assets/images/bg1.png');
  background-size: cover;
  background-position: center;
  padding: 44px 16px 32px;
  position: relative;
  color: #fff;

  &::before {
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: linear-gradient(to bottom, rgba(0,0,0,0.3), rgba(0,0,0,0.1));
  }

  .header {
    position: relative;
    display: flex;
    justify-content: space-between;
    align-items: center;
    z-index: 1;

    .location {
      display: flex;
      align-items: center;
      font-size: 16px;
      color: #fff;
      gap: 4px;
    }

    .header-right {
      display: flex;
      gap: 16px;
    }
  }

  .banner-content {
    position: relative;
    z-index: 1;
    margin-top: 24px;

    h2 {
      font-size: 24px;
      font-weight: 600;
      margin: 0;
      margin-bottom: 8px;
    }

    p {
      font-size: 14px;
      margin: 0;
      margin-bottom: 16px;
      opacity: 0.9;
    }

    .more-btn {
      color: #fff;
      border-color: #fff;
    }
  }
}

.todo-section {
  margin: 16px;
  background: #fff;
  border-radius: 8px;
  padding: 16px;

  .todo-header {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 12px;

    .todo-left {
      display: flex;
      align-items: center;
      gap: 8px;
      font-size: 16px;
      color: #333;

      .todo-count {
        color: #ff4d4f;
        font-size: 14px;
      }
    }
  }

  .notification-bar {
    display: flex;
    align-items: center;
    gap: 8px;
    background: #fff7e6;
    padding: 8px 12px;
    border-radius: 4px;
    color: #ff4d4f;
    font-size: 14px;

    .notification-text {
      flex: 1;
    }
  }
}

.function-grid {
  margin: 16px;
  display: grid;
  grid-template-columns: repeat(4, 1fr);
  gap: 16px;
  background: #fff;
  border-radius: 8px;
  padding: 16px;

  .grid-item {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 8px;

    .icon-wrapper {
      width: 48px;
      height: 48px;
      border-radius: 12px;
      display: flex;
      align-items: center;
      justify-content: center;
    }

    .grid-text {
      font-size: 12px;
      color: #333;
      text-align: center;
    }
  }
}

.eco-section {
  margin: 16px;
  background: #fff;
  border-radius: 8px;
  padding: 16px;

  .section-title {
    font-size: 18px;
    color: #333;
    margin: 0;
    margin-bottom: 16px;
  }

  .eco-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 16px;

    .eco-item {
      background: #f5f5f5;
      border-radius: 8px;
      padding: 16px;
      display: flex;
      align-items: center;
      gap: 12px;

      .eco-content {
        flex: 1;

        h4 {
          font-size: 16px;
          color: #333;
          margin: 0;
          margin-bottom: 4px;
        }

        p {
          font-size: 12px;
          color: #666;
          margin: 0;
        }
      }

      img {
        width: 48px;
        height: 48px;
        border-radius: 8px;
        object-fit: cover;
      }
    }
  }
}
</style>
