<!--
Codes Generated By ebiz-lowcode:
http://www.ebiz-interactive.com/
-->

<template>
  <div class="container" style='height: 100vh;'>
    <van-empty  style='height: 100%' description='这里什么都没有' :image='notFoundImg' image-size='100vw' />
  </div>
</template>

<script>
import notFoundImg from '@/assets/images/404.jpg'
import {Empty} from 'vant'
export default {
  components: {
    [Empty.name]:Empty
  },
  props: {},
  data() {
    return {
      notFoundImg,
    }
  },
  computed: {},
  watch: {},
  created() {},
  mounted() {},
  methods: {
    // H5提交函数
    submitForm() {}
  }
}
</script>

<style lang="scss"></style>

<style lang="scss" scoped></style>
